"""Config module"""
from .base_config import BASE_URL, API_ENDPOINTS, PAGE_ROUTES, TIMEOUT, TEST_DATA, REPORT_DIR, RETRY_COUNT, RETRY_DELAY

__all__ = ['BASE_URL', 'API_ENDPOINTS', 'PAGE_ROUTES', 'TIMEOUT', 'TEST_DATA', 'REPORT_DIR', 'RETRY_COUNT', 'RETRY_DELAY']