server:
  port: 8080

spring:
  application:
    name: dictation

  datasource:
    url: jdbc:sqlite:src/main/resources/dictation.db
    driver-class-name: org.sqlite.JDBC

  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true

  threads:
    virtual:
      enabled: true

# 日志配置
logging:
  level:
    com.yhj.dictation: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

# 跨域配置
cors:
  allowed-origins: "*"
  allowed-methods: "*"
  allowed-headers: "*"
  allow-credentials: true